"""Midtrain a base model on sentientfutures/animal-welfare-training-claude before the decision recipe: a LoRA trained with
next-token loss, merged into the base in fp32.

    uv run python scripts/midtrain_gev.py build --arm sdf --out runs/gev/hc/mt-sdf          # CPU: tokenize and pack
    uv run python scripts/midtrain_gev.py train --out runs/gev/hc/mt-sdf                    # GPU: train, merge, save

The two configs of the dataset (CC0, generated by Claude models against Claude's constitution; every language kept):
`sdf` is pretraining-style documents, each one its `content` and an end-of-text token, with loss on every token; `dad` is
difficult-advice Q&A, each pair in the base tokenizer's chat template (thinking off), with loss on the assistant's turn
only. `--arm sdf` trains on the documents, `--arm sdf-dad` on both. General text from FineWeb-Edu (sample-10BT, ODC-By)
is mixed in at `--general_ratio` tokens per corpus token, fresh documents each epoch, so the model does not learn that the
whole world is this corpus. `--arm general` trains on general text alone, as many tokens as `--arm sdf` would (the control).
Each epoch's documents are shuffled together and packed into `--seq` token chunks across document boundaries.

`build` writes chunks.pt (input ids and labels, every chunk in training order, plus a held-out set of general text) and
data.json (revisions, token counts). `train` loads the base in bf16 under a LoRA (the same target modules as kev.train's
`--lora_targets all`), runs AdamW with a cosine schedule, and reports the held-out general loss before and after; then it
reloads the base in fp32 on the CPU, merges the adapter and saves the merged model to OUT/merged (fp32, since rounding
W + delta to the base's bf16 would erase much of a small update). OUT/merged is a base model for kev.train:
`--base $PWD/OUT/merged --base_revision <midtrain.json's adapter_sha256>`. A preempted run (SIGTERM) saves a resume point
after its current step and exits 143; rerunning `train` continues from it, as does the save every `--save_every_minutes`.
"""
import argparse
import json
import math
import os
import random
import signal
import sys
import threading
import time
from pathlib import Path

import torch
from huggingface_hub import hf_hub_download

from kev.suite import digest, write_json

REPO, REVISION = "sentientfutures/animal-welfare-training-claude", "d5d60c85cf575e2ccae7497bf95a7508a8f9b1c0"
GENERAL, GENERAL_CONFIG, GENERAL_REVISION = "HuggingFaceFW/fineweb-edu", "sample-10BT", "87f09149ef4734204d70ed1d046ddc9ca3f2b8f9"
BASE, BASE_REVISION = "Qwen/Qwen3.5-4B-Base", "1001bb4d826a52d1f399e183466143f4da7b741b"
TARGETS = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj",
           "in_proj_qkv", "in_proj_z", "in_proj_a", "in_proj_b", "out_proj"]   # kev.model.DecisionModel's `all` on a hybrid base


def corpus(tok, config):
    """[(ids, labels)] per record of one config, labels -100 where no loss is taken."""
    path = hf_hub_download(REPO, f"{config}/{config}_corpus.jsonl", repo_type="dataset", revision=REVISION)
    docs = []
    for row in map(json.loads, open(path, encoding="utf-8")):
        if config == "sdf":
            ids = tok(row["content"], add_special_tokens=False)["input_ids"] + [tok.eos_token_id]
            docs.append((ids, ids))
            continue
        user = [{"role": "user", "content": row["user_prompt"]}]
        prompt = tok.apply_chat_template(user, tokenize=False, add_generation_prompt=True, enable_thinking=False)
        full = tok.apply_chat_template(user + [{"role": "assistant", "content": row["assistant_response"]}], tokenize=False, enable_thinking=False)
        if not full.startswith(prompt): raise ValueError("the chat template's prompt is not a prefix of the full conversation")
        head = tok(prompt, add_special_tokens=False)["input_ids"]
        tail = tok(full[len(prompt):], add_special_tokens=False)["input_ids"] + [tok.eos_token_id]
        docs.append((head + tail, [-100] * len(head) + tail))
    return docs


def general_docs(tok):
    """FineWeb-Edu documents in the dataset's order, each tokenized with an end-of-text token, as an endless iterator."""
    from datasets import load_dataset
    for row in load_dataset(GENERAL, GENERAL_CONFIG, split="train", streaming=True, revision=GENERAL_REVISION):
        ids = tok(row["text"], add_special_tokens=False)["input_ids"] + [tok.eos_token_id]
        yield ids, ids


def take(stream, tokens):
    docs, n = [], 0
    while n < tokens:
        docs.append(next(stream))
        n += len(docs[-1][0])
    return docs


def pack(docs, seq):
    ids = [t for d, _ in docs for t in d]
    labels = [t for _, l in docs for t in l]
    n = len(ids) // seq
    return torch.tensor(ids[:n * seq]).view(n, seq), torch.tensor(labels[:n * seq]).view(n, seq)


def build(a):
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(a.base, revision=a.base_revision)
    configs = {"sdf": ["sdf"], "sdf-dad": ["sdf", "dad"], "general": ["sdf"]}[a.arm]
    docs = [d for c in configs for d in corpus(tok, c)]
    corpus_tokens = sum(len(d) for d, _ in docs)
    stream = general_docs(tok)
    heldout = pack(take(stream, a.heldout_tokens), a.seq)
    rng = random.Random(a.seed)
    chunks, general_tokens = [], 0
    for _ in range(a.epochs):
        general = take(stream, round(((a.arm == "general") + a.general_ratio) * corpus_tokens))
        general_tokens += sum(len(d) for d, _ in general)
        epoch = (general if a.arm == "general" else docs + general)[:]
        rng.shuffle(epoch)
        chunks.append(pack(epoch, a.seq))
    stream.close()   # an open streaming dataset keeps the interpreter from exiting
    ids, labels = torch.cat([c[0] for c in chunks]), torch.cat([c[1] for c in chunks])
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    torch.save({"ids": ids, "labels": labels, "heldout_ids": heldout[0], "heldout_labels": heldout[1]}, out / "chunks.pt")
    info = {"arm": a.arm, "base": a.base, "base_revision": a.base_revision, "seed": a.seed, "seq": a.seq, "epochs": a.epochs,
            "general_ratio": a.general_ratio, "dataset": {"repo": REPO, "revision": REVISION, "configs": configs if a.arm != "general" else []},
            "general": {"repo": GENERAL, "config": GENERAL_CONFIG, "revision": GENERAL_REVISION},
            "corpus_records": len(docs), "corpus_tokens": corpus_tokens if a.arm != "general" else 0,
            "general_tokens": general_tokens, "chunks": len(ids), "loss_tokens": int((labels != -100).sum()),
            "heldout_chunks": len(heldout[0]), "chunks_sha256": digest(out / "chunks.pt")}
    write_json(out / "data.json", info)
    print(json.dumps(info, indent=1))


def evaluate(model, ids, labels, batch):
    model.eval()
    total, n = 0.0, 0
    with torch.no_grad(), torch.autocast("cuda", dtype=torch.bfloat16):
        for i in range(0, len(ids), batch):
            x, y = ids[i:i + batch].cuda(), labels[i:i + batch].cuda()
            k = int((y[:, 1:] != -100).sum())
            total += model(input_ids=x, labels=y).loss.item() * k
            n += k
    model.train()
    return total / n


def save_resume(path, model, opt, sched, step, settings):
    from peft import get_peft_model_state_dict
    tmp = path.with_suffix(".tmp")
    torch.save({"adapter": get_peft_model_state_dict(model), "opt": opt.state_dict(), "sched": sched.state_dict(), "step": step, "settings": settings,
                "rng": torch.get_rng_state(), "cuda_rng": torch.cuda.get_rng_state()}, tmp)
    tmp.replace(path)
    print(f"resume point at step {step}", flush=True)


def train(a):
    from peft import LoraConfig, PeftModel, get_peft_model, set_peft_model_state_dict
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from kev.train import wandb_run
    out = Path(a.out)
    if (out / "midtrain.json").exists(): sys.exit(f"{out} is already midtrained (midtrain.json)")
    info = json.loads((out / "data.json").read_text(encoding="utf-8"))
    data = torch.load(out / "chunks.pt")
    if digest(out / "chunks.pt") != info["chunks_sha256"]: raise ValueError("chunks.pt does not match data.json")
    torch.manual_seed(a.seed)
    model = AutoModelForCausalLM.from_pretrained(info["base"], revision=info["base_revision"], dtype=torch.bfloat16, device_map="cuda")
    model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
    model.enable_input_require_grads()
    model = get_peft_model(model, LoraConfig(task_type="CAUSAL_LM", r=a.lora, lora_alpha=2 * a.lora, lora_dropout=0.05, target_modules=TARGETS))
    for p in model.parameters():
        if p.requires_grad: p.data = p.data.float()   # fp32 adapter on the bf16 base
    steps = min(len(data["ids"]) // (a.batch * a.accum), a.max_steps or 1 << 62)
    opt = torch.optim.AdamW([p for p in model.parameters() if p.requires_grad], lr=a.lr, weight_decay=0.0)
    warmup = max(1, round(a.warmup * steps))
    sched = torch.optim.lr_scheduler.LambdaLR(opt, lambda s: min(1.0, (s + 1) / warmup) * 0.5 * (1 + math.cos(math.pi * min(1.0, s / steps))))
    resume, step = out / "resume.pt", 0
    settings = {k: getattr(a, k) for k in ("lora", "lr", "warmup", "batch", "accum", "seed", "max_steps")}
    log = {"before_heldout_loss": None, "steps": steps, "losses": []}
    if (out / "train_log.json").exists(): log = json.loads((out / "train_log.json").read_text(encoding="utf-8"))
    if resume.exists():
        state = torch.load(resume, weights_only=False)
        if state.get("settings", settings) != settings: sys.exit(f"resume point trained with {state['settings']}, not {settings}")
        set_peft_model_state_dict(model, state["adapter"])
        opt.load_state_dict(state["opt"]); sched.load_state_dict(state["sched"]); step = state["step"]
        torch.set_rng_state(state["rng"]); torch.cuda.set_rng_state(state["cuda_rng"])
        log["losses"] = [x for x in log["losses"] if x[0] <= step]   # a log written after this resume point
        print(f"resumed at step {step} of {steps}", flush=True)
    if log["before_heldout_loss"] is None:
        log["before_heldout_loss"] = evaluate(model, data["heldout_ids"], data["heldout_labels"], a.batch)
        print(f"held-out general loss before: {log['before_heldout_loss']:.4f}", flush=True)
    run = wandb_run(a, out)
    terminated = threading.Event()
    signal.signal(signal.SIGTERM, lambda *_: terminated.set())
    saved, t0 = time.time(), time.time()
    model.train()
    while step < steps:
        total = 0.0
        for m in range(a.accum):
            i = (step * a.accum + m) * a.batch
            x, y = data["ids"][i:i + a.batch].cuda(), data["labels"][i:i + a.batch].cuda()
            with torch.autocast("cuda", dtype=torch.bfloat16):
                loss = model(input_ids=x, labels=y).loss / a.accum
            loss.backward()
            total += loss.item()
        torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1.0)
        opt.step(); sched.step(); opt.zero_grad(set_to_none=True)
        step += 1
        log["losses"].append([step, total])
        if run: run.log({"loss": total, "lr": sched.get_last_lr()[0]}, step=step)
        if step % 10 == 0:
            rate = (time.time() - t0) / 10
            t0 = time.time()
            print(f"step {step}/{steps} loss {total:.4f} lr {sched.get_last_lr()[0]:.2e} {rate:.1f}s/step", flush=True)
        if terminated.is_set() or time.time() - saved > 60 * a.save_every_minutes:
            write_json(out / "train_log.json", log)   # first, so a resume point never lacks its log
            save_resume(resume, model, opt, sched, step, settings)
            saved = time.time()
            if terminated.is_set():
                print(f"stopped after step {step}; rerun to continue", flush=True)
                sys.exit(143)
    signal.signal(signal.SIGTERM, signal.SIG_DFL)   # past the last step a rerun redoes the rest from the resume point
    log["after_heldout_loss"] = evaluate(model, data["heldout_ids"], data["heldout_labels"], a.batch)
    print(f"held-out general loss after: {log['after_heldout_loss']:.4f} (before {log['before_heldout_loss']:.4f})", flush=True)
    model.save_pretrained(out / "adapter")
    write_json(out / "train_log.json", log)
    if run: run.finish()
    del model, opt, data
    torch.cuda.empty_cache()

    # merge in fp32 on the CPU
    tok = AutoTokenizer.from_pretrained(info["base"], revision=info["base_revision"])
    base = AutoModelForCausalLM.from_pretrained(info["base"], revision=info["base_revision"], dtype=torch.float32)
    merged = PeftModel.from_pretrained(base, out / "adapter").merge_and_unload()
    merged.save_pretrained(out / "merged")
    tok.save_pretrained(out / "merged")
    adapter_sha = digest(out / "adapter" / "adapter_model.safetensors")
    write_json(out / "midtrain.json", {**info, "lora": a.lora, "lr": a.lr, "batch": a.batch, "accum": a.accum, "warmup": a.warmup,
                                       "steps": steps, "adapter_sha256": adapter_sha, "merged_dtype": "float32",
                                       "before_heldout_loss": log["before_heldout_loss"], "after_heldout_loss": log["after_heldout_loss"],
                                       "final_loss": log["losses"][-1][1]})
    resume.unlink(missing_ok=True)
    print(f"merged into {out / 'merged'}; adapter sha256 {adapter_sha}", flush=True)
    print("MIDTRAINDONE", flush=True)


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("--arm", choices=["sdf", "sdf-dad", "general"], required=True)
    b.add_argument("--base", default=BASE)
    b.add_argument("--base_revision", default=BASE_REVISION)
    b.add_argument("--epochs", type=int, default=2)
    b.add_argument("--general_ratio", type=float, default=1.0, help="general tokens per corpus token, each epoch")
    b.add_argument("--seq", type=int, default=2048)
    b.add_argument("--heldout_tokens", type=int, default=400_000, help="general text held out for the before/after loss")
    b.add_argument("--seed", type=int, default=0)
    b.add_argument("--out", required=True)
    t = sub.add_parser("train")
    t.add_argument("--out", required=True)
    t.add_argument("--lora", type=int, default=64)
    t.add_argument("--lr", type=float, default=1e-4)
    t.add_argument("--warmup", type=float, default=0.03, help="fraction of the steps")
    t.add_argument("--batch", type=int, default=1)
    t.add_argument("--accum", type=int, default=16)
    t.add_argument("--seed", type=int, default=0)
    t.add_argument("--save_every_minutes", type=float, default=10)
    t.add_argument("--max_steps", type=int, default=0, help="stop early (a smoke test); 0 = every chunk")
    a = ap.parse_args()
    build(a) if a.cmd == "build" else train(a)


if __name__ == "__main__":
    main()
